trigger:
- main

pool:
vmImage: 'ubuntu-latest' 

variables:
   repositoryName: 'cebundyacr.azurecr.io'

steps:
- task: Docker@2
inputs:
   containerRegistry: 'azure resource manager jukullam'
   repository: $(repositoryName)
   command: 'buildAndPush'
   Dockerfile: '**/Dockerfile'
