trigger:
- main

pool:
  name: cebundy

variables:
  imageName: 'your-image-name'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: 'azure resource manager jukullam'
    azureContainerRegistry: 'cebundyacr.azurescr.io'
    command: 'Build an image'
    imageName: $(Build.Repository.Name):$(Build.BuildId)
    dockerFile: '**/Dockerfile'
    includeLatestTag: true
    additionalImageTags: |
      $(tag)
    qualifyImageName: true
    containerRegistryType: 'Azure Container Registry'

- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: 'azure resource manager jukullam'
    azureContainerRegistry: 'cebundyacr.azurescr.io'
    command: 'Push an image'
    imageName: $(Build.Repository.Name):$(Build.BuildId)
    dockerFile: '**/Dockerfile'
    includeLatestTag: true
    additionalImageTags: |
      $(tag)
    qualifyImageName: true
    containerRegistryType: 'Azure Container Registry'